apiVersion: v1
kind: ConfigMap
metadata:
  name: evolution-api-config
data:
  AUTHENTICATION_TYPE: "apikey"
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
  DATABASE_ENABLED: "false"
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_GLOBAL_EVENTS: "true"
  SERVER_URL: "https://clinica-937b0859.northcentralus.cloudapp.azure.com/evolution"
  DEL_INSTANCE: "false"
  LOG_LEVEL: "ERROR"
  LOG_COLOR: "true"
