apiVersion: v1
kind: Service
metadata:
  name: ms-ms-pacientes-nextjs
spec:
  selector:
    app: ms-ms-pacientes-nextjs
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
