apiVersion: v1
kind: Service
metadata:
  name: ms-springboot-gestion
spec:
  selector:
    app: ms-springboot-gestion
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
